version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_ADDR: redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
